
#type: args

train:
  epochs: 40
  batch_size: 96
  lr: 1.0e-4

model:
  norm: False
  fmamba: True
  edepth: 3
  mdepth: 3
  pdepth: 3
  dense_channel: 16
  compress_factor: 0.3
  num_tscblocks: 5
  sampling_rate: 16000
  n_fft: 64
  hop_size: 8
  win_size: 64
  beta: 2
  loss_fn: "v8"

